### ISSUE TITLE
__init__.py needs to know that it cannot import dominos when dominos is not installed

### ISSUE THREAD

**Issue by devsnek** [tomasbasham/dominos#1]
```
$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from dominos.version import Version
  File "/Users/Gus/Downloads/dominos/dominos/__init__.py", line 1, in <module>
    from dominos import Dominos
ImportError: cannot import name 'Dominos'
```

i fixed this by commenting out that line, installing, then uncommenting the installed one

**Comment by tomasbasham** [comment]
Thanks for the feedback. This package is still in alpha and has not been tested with python 3.
