### ISSUE TITLE
Lib not working anymore, got 403

### ISSUE THREAD

**Issue by voron434** [tomasbasham/dominos#9]
Trying to run your example from REAME:

Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
```
>>> from dominos.api import Client
>>> api = Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ilya/Desktop/subl/venv/lib/python3.6/site-packages/dominos/api.py", line 50, in __init__
    self.reset_session()
  File "/home/ilya/Desktop/subl/venv/lib/python3.6/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/home/ilya/Desktop/subl/venv/lib/python3.6/site-packages/dominos/api.py", line 64, in reset_session
    raise self.ApiError('Failed to clear session: {}'.format(response.status_code))
dominos.api.ApiError: Failed to clear session: 403
```

**Comment by Ali-Parandeh** [comment]
I tested the code in July I could receive data from the API.

See the attached image.

![screenshot_20190709_233656](https://user-images.githubusercontent.com/43654026/60927622-7900ad80-a2a2-11e9-9c6d-09270a11173d.png)

**Comment by Ali-Parandeh** [comment]
I tested the library in July and it was working fine - The API was providing data to my requests. You can use postman to check the api urls.
